import React, { useState, useEffect, createElement } from "react";

function Word({ selectedDifficulty }) {
  let hard_words = [
    "abundant",
    "benevolent",
    "cautious",
    "diligent",
    "efficient",
    "facetious",
    "generous",
    "hypothetical",
    "innocuous",
    "juxtapose",
    "keen",
    "laconic",
    "meticulous",
    "notorious",
    "obscure",
    "perceptive",
    "quaint",
    "reliable",
    "sagacious",
    "tenacious",
    "ubiquitous",
    "vivid",
    "waning",
    "xenophobic",
    "yawning",
    "zealous",
    "agreeable",
    "bold",
    "candid",
    "dedicated",
    "eager",
    "faithful",
    "gregarious",
    "humble",
    "intuitive",
    "jubilant",
    "kind",
    "luminous",
    "motivated",
    "nurturing",
    "optimistic",
    "patient",
    "quizzical",
    "resilient",
    "sincere",
    "trustworthy",
    "unique",
    "versatile",
    "witty",
    "xenial",
    "youthful",
    "zealous",
    "admirable",
    "brilliant",
    "curious",
    "decisive",
    "eloquent",
    "friendly",
    "genuine",
    "hopeful",
    "inspired",
    "joyful",
    "knowledgeable",
    "loyal",
    "mindful",
    "noble",
    "observant",
    "persistent",
    "quiet",
    "resourceful",
    "steadfast",
    "thoughtful",
    "upbeat",
    "valiant",
    "wise",
    "youthful",
    "zealous",
    "ambitious",
    "brave",
    "confident",
    "dedicated",
    "enthusiastic",
    "forgiving",
    "gracious",
    "helpful",
    "imaginative",
    "joyful",
    "keen",
    "logical",
    "motivated",
    "neat",
    "organized",
    "pragmatic",
    "quick-witted",
    "respectful",
    "supportive",
    "trusting",
    "understanding",
    "vibrant",
    "warm",
    "xenodochial",
    "youthful",
    "zealous",
    "adaptable",
    "brilliant",
    "considerate",
    "determined",
    "empathetic",
    "flexible",
    "grateful",
    "honest",
    "innovative",
    "jovial",
    "knowledgeable",
    "logical",
    "modest",
    "nurturing",
    "optimistic",
    "practical",
    "quick",
    "reliable",
    "sensible",
    "tolerant",
    "uplifting",
    "vigilant",
    "welcoming",
    "xenial",
    "young",
    "zealous",
  ];

  const [randomWord, setRandomWord] = useState("");

  useEffect(() => {
    let randomIndex = Math.floor(Math.random() * hard_words.length);
    let randomWordFromArray = hard_words[randomIndex];
    setRandomWord(randomWordFromArray);
  }, [selectedDifficulty]);

  let map = randomWord
    .split("")
    .map((item, index) =>
      createElement("div", { key: index, className: "letter" }, item)
    );
  map.push(
    createElement("div", { key: "space", className: "letter space" }, " ")
  );

  return map;
}

export default Word;
